name: flutter_github_repo_explorer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
